package:
  name: tigre_python
  version: "0.0.0"
souce:
  url: https://github.com/Reuben481/tigre.git

build:
  build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyinstrument = pyinstrument:main
    #
    # Would create an entry point called pyinstrument that calls pyinstrument.main()

    - tigre_python = tigre_python.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - pwd
    - conda install tigre_python 
  # Python imports
  imports:
    - sys
    - tigre_python


about:
  home: url/not/specified.org
  license: notspecified
  
  


# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
